### ISSUE TITLE
Problem: occasional uniqueness constrain violation error in account update

### ISSUE THREAD

**Issue by yihuang** [crypto-org-chain/cronos#1549]
```
[90m7:36AM[0m [32mINF[0m [1mreceived complete proposal block[0m [36mhash=[0mF3C5E20633C02E20C5681E9939CD5C2A32A81AC40A20D46C654EABEBBF7EFE0D [36mheight=[0m6 [36mmodule=[0mconsensus [36mserver=[0mnode
[90m7:36AM[0m [31mERR[0m [1mpanic recovered in runTx[0m [36merr=[0m"recovered: collections: conflict: index uniqueness constrain violation: 131\nstack:\ngoroutine 3579 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x5e\ngithub.com/cosmos/cosmos-sdk/baseapp.NewBaseApp.newDefaultRecoveryMiddleware.func5({0x4f09be0, 0xc00720a340})\n\tgithub.com/cosmos/cosmos-sdk/baseapp/recovery.go:74 +0x25\ngithub.com/cosmos/cosmos-sdk/baseapp.NewBaseApp.newDefaultRecoveryMiddleware.newRecoveryMiddleware.func7({0x4f09be0?, 0xc00720a340?})\n\tgithub.com/cosmos/cosmos-sdk/baseapp/recovery.go:42 +0x2d\ngithub.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x4f09be0, 0xc00720a340}, 0x10?)\n\tgithub.com/cosmos/cosmos-sdk/baseapp/recovery.go:31 +0x2f\ngithub.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x4f09be0, 0xc00720a340}, 0x0?)\n\tgithub.com/cosmos/cosmos-sdk/baseapp/recovery.go:36 +0x53\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTxWithMultiStore.func1()\n\tgithub.com/cosmos/cosmos-sdk/baseapp/baseapp.go:866 +0x156\npanic({0x4f09be0?, 0xc00720a340?})\n\truntime/panic.go:770 +0x132\ngithub.com/cosmos/cosmos-sdk/x/auth/keeper.AccountKeeper.SetAccount({{0x751dfc8, 0xc000e010d0}, {0x750b0e0, 0xc0018106e0}, {0x756b140, 0xc00092bb50}, 0xc002429f20, {0x54b3ccc, 0x3}, 0x6d78578, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk/x/auth/keeper/account.go:61 +0x96\ngithub.com/cosmos/cosmos-sdk/x/bank/keeper.BaseSendKeeper.ensureAccountCreated({{{0x756b140, 0xc00092bb50}, {0x750b0e0, 0xc0018106f0}, {0x7574950, 0xc001b74500}, {0x7555338, 0xc0002a2a80}, {0xc001b99ec0, {0xc0016920c0, ...}, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk/x/bank/keeper/send.go:242 +0xf9\ngithub.com/cosmos/cosmos-sdk/x/bank/keeper.BaseSendKeeper.SendCoins({{{0x756b140, 0xc00092bb50}, {0x750b0e0, 0xc0018106f0}, {0x7574950, 0xc001b74500}, {0x7555338, 0xc0002a2a80}, {0xc001b99ec0, {0xc0016920c0, ...}, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk/x/bank/keeper/send.go:229 +0x225\ngithub.com/evmos/ethermint/x/evm/keeper.(*Keeper).Transfer(_, {{0x754ab00, 0xc006fe5590}, {0x7567ae0, 0xc006fe55c0}, {{0x0, 0x0}, {0xc000f62670, 0xc}, 0x6, ...}, ...}, ...)\n\tgithub.com/evmos/ethermint/x/evm/keeper/statedb.go:76 +0xd7\ngithub.com/evmos/ethermint/x/evm/statedb.(*StateDB).Transfer.func1({{0x754ab00, 0xc006fe5590}, {0x7567ae0, 0xc006fe55c0}, {{0x0, 0x0}, {0xc000f62670, 0xc}, 0x6, {0x25c8b724, ...}, ...}, ...})\n\tgithub.com/evmos/ethermint/x/evm/statedb/statedb.go:402 +0xa6\ngithub.com/evmos/ethermint/x/evm/statedb.(*StateDB).ExecuteNativeAction(0xc0010e5608, {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)\n\tgithub.com/evmos/ethermint/x/evm/statedb/statedb.go:368 +0x1d9\ngithub.com/evmos/ethermint/x/evm/statedb.(*StateDB).Transfer(0xc0010e5608, {0xf0, 0xc8, 0x7b, 0x21, 0xd1, 0x2e, 0x1, 0xfe, 0x3b, ...}, ...)\n\tgithub.com/evmos/ethermint/x/evm/statedb/statedb.go:401 +0x20a\ngithub.com/evmos/ethermint/x/evm/statedb.Transfer({0x759fdf0?, 0xc0010e5608?}, {0xf0, 0xc8, 0x7b, 0x21, 0xd1, 0x2e, 0x1, 0xfe, ...}, ...)\n\tgithub.com/evmos/ethermint/x/evm/statedb/statedb.go:47 +0x57\ngithub.com/ethereum/go-ethereum/core/vm.(*EVM).Call(0xc00662fa40, {0x750cca0, 0xc006fd51e8}, {0xad, 0xd3, 0xff, 0x5f, 0xbc, 0xca, 0x2f, ...}, ...)\n\tgithub.com/ethereum/go-ethereum/core/vm/evm.go:200 +0x594\ngithub.com/evmos/ethermint/x/evm/keeper.(*Keeper).ApplyMessageWithConfig(_, {{0x754a828, 0x9a77ec0}, {0x7567ae0, 0xc006fe5440}, {{0x0, 0x0}, {0xc000f62670, 0xc}, 0x6, ...}, ...}, ...)\n\tgithub.com/evmos/ethermint/x/evm/keeper/state_transition.go:387 +0x8f7\ngithub.com/evmos/ethermint/x/evm/keeper.(*Keeper).ApplyTransaction(_, {{0x754a828, 0x9a77ec0}, {0x7567ae0, 0xc006fe52f0}, {{0x0, 0x0}, {0xc000f62670, 0xc}, 0x6, ...}, ...}, ...)\n\tgithub.com/evmos/ethermint/x/evm/keeper/state_transition.go:188 +0x272\ngithub.com/evmos/ethermint/x/evm/keeper.(*Keeper).EthereumTx(0xc002006fc0, {0x754ab00?, 0xc006fe53e0?}, 0xc006fccf00)\n\tgithub.com/evmos/ethermint/x/evm/keeper/msg_server.go:57 +0x2e8\ngithub.com/evmos/ethermint/x/evm/types._Msg_EthereumTx_Handler.func1({0x754ab00?, 0xc006fe53e0?}, {0x544f9e0?, 0xc006fccf00?})\n\tgithub.com/evmos/ethermint/x/evm/types/tx.pb.go:614 +0xcb\ngithub.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).registerMsgServiceHandler.func2.1({0x754a860, 0xc006fec808}, {0xc00712def8?, 0x1c361c5?}, 0x388?, 0xc006fbf008)\n\tgithub.com/cosmos/cosmos-sdk/baseapp/msg_service_router.go:175 +0x8a\ngithub.com/evmos/ethermint/x/evm/types._Msg_EthereumTx_Handler({0x5484e40, 0xc002006fc0}, {0x754a860, 0xc006fec808}, 0x6d79a30, 0xc006fc5dc0)\n\tgithub.com/evmos/ethermint/x/evm/types/tx.pb.go:616 +0x143\ngithub.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).registerMsgServiceHandler.func2({{0x754a828, 0x9a77ec0}, {0x7567ae0, 0xc006fe52f0}, {{0x0, 0x0}, {0xc000f62670, 0xc}, 0x6, {0x25c8b724, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk/baseapp/msg_service_router.go:198 +0x37f\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runMsgs(_, {{0x754a828, 0x9a77ec0}, {0x7567ae0, 0xc006fe52f0}, {{0x0, 0x0}, {0xc000f62670, 0xc}, 0x6, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk/baseapp/baseapp.go:1047 +0x26b\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTxWithMultiStore(0xc0025e4b48, 0x7, {0xc006f538c0, 0x105, 0x105}, 0x1c41c05?, {0x7566ac0, 0xc006fc94a0}, 0xc00732e090)\n\tgithub.com/cosmos/cosmos-sdk/baseapp/baseapp.go:983 +0x138c\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).deliverTxWithMultiStore(0xc0025e4b48, {0xc006f538c0?, 0xc007133e70?, 0x1c361c5?}, 0x10?, {0x7566ac0?, 0xc006fc94a0?}, 0xc006fc94a0?)\n\tgithub.com/cosmos/cosmos-sdk/baseapp/baseapp.go:784 +0xe8\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).executeTxs.func1(0x52c2520?, {0x7566ac0?, 0xc006fc94a0?}, 0xc006fc5800?)\n\tgithub.com/cosmos/cosmos-sdk/baseapp/abci.go:846 +0x5c\ngithub.com/crypto-org-chain/cronos/v2/app.New.STMTxExecutor.func5.1(0x17, {0x7540f10, 0xc006fc5800})\n\tgithub.com/evmos/ethermint/app/executor.go:66 +0xe4\ngithub.com/crypto-org-chain/go-block-stm.(*Executor).execute(0xc00732e270, 0x17)\n\tgithub.com/crypto-org-chain/go-block-stm/executor.go:82 +0xf3\ngithub.com/crypto-org-chain/go-block-stm.(*Executor).TryExecute(0xc00732e270, {0x10000c00184baa8?, 0xc00373e380?})\n\tgithub.com/crypto-org-chain/go-block-stm/executor.go:65 +0x31\ngithub.com/crypto-org-chain/go-block-stm.(*Executor).Run(0xc00732e270)\n\tgithub.com/crypto-org-chain/go-block-stm/executor.go:56 +0x6e\ngithub.com/crypto-org-chain/go-block-stm.ExecuteBlock.func1()\n\tgithub.com/crypto-org-chain/go-block-stm/stm.go:38 +0x4d\ncreated by github.com/crypto-org-chain/go-block-stm.ExecuteBlock in goroutine 4275\n\tgithub.com/crypto-org-chain/go-block-stm/stm.go:36 +0x1a9\n: panic" [36mmodule=[0mserver
[90m7:36AM[0m [32mINF[0m [1mfinalizing commit of block[0m [36mhash=[0mF3C5E20633C02E20C5681E9939CD5C2A32A81AC40A20D46C654EABEBBF7EFE0D [36mheight=[0m6 [36mmodule=[0mconsensus [36mnum_txs=[0m30 [36mroot=[0m451B20B5D345CAC63477CCBB5AFE7ED1ACB7560BE5E1BB5C92AE2B259A0856F2 [36mserver=[0mnode
[90m7:36AM[0m [32mINF[0m [1mfinalized block[0m [36mblock_app_hash=[0mC86CBAF721987ED6D127AE66EE35C2AE1CFB21F0F54D7F83562E8FE05AC5EE69 [36mheight=[0m6 [36mmodule=[0mstate [36mnum_txs_res=[0m30 [36mnum_val_updates=[0m0 [36
```

the account number unique index is violated.

**Comment by yihuang** [comment]
it's expected in block-stm, because it could read conflicted states, and it'll eventually retry itself.
so the real issue is just to have cleaner log.
