### ISSUE TITLE
Problem: Node stopped working

### ISSUE THREAD

**Issue by gap370** [crypto-org-chain/cronos#256]
I met this error:
```
panic: Failed to process committed block (550074:51F5B34B5FE2DCC9DEB17BA2C531D049AEB8061E1122E392B65B0EC476DE8CA4): wrong Block.Header.AppHash.  Expected 420E759A140861B41EA8C6405A9127F1F688A9DFDC4CC68F18385FA1665E31E2, got 09807D961B28C9D30D2280D530178481CFC2ADBE9B6A77B272F69C3B7342A1A1

goroutine 136 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc00144d180, 0x0)
        /go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/blockchain/v0/reactor.go:401 +0x1265
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
        /go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/blockchain/v0/reactor.go:110 +0x85
```
and if I try to rerun, it gives:
```
5:54PM ERR failed init node error="error during handshake: error on replay: wrong Block.Header.AppHash.  Expected 420E759A140861B41EA8C6405A9127
F1F688A9DFDC4CC68F18385FA1665E31E2, got 09807D961B28C9D30D2280D530178481CFC2ADBE9B6A77B272F69C3B7342A1A1"                                       
Error: error during handshake: error on replay: wrong Block.Header.AppHash.  Expected 420E759A140861B41EA8C6405A9127F1F688A9DFDC4CC68F18385FA166
5E31E2, got 09807D961B28C9D30D2280D530178481CFC2ADBE9B6A77B272F69C3B7342A1A1  
```

**Comment by thomas-nguy** [comment]
Which version do you use?

Did you try to change version while using the same data?

**Comment by gap370** [comment]
0.6.4
Yes, I did upgrade version and used the same data.

**Comment by yihuang** [comment]
probably same issue as: https://github.com/crypto-org-chain/cronos/issues/284, closing for now.
