### ISSUE TITLE
Problems starting a testnet node

### ISSUE THREAD

**Issue by tkopicbeyondi** [crypto-org-chain/cronos#353]
Hello,

I've been following the tutorial here:
https://cronos.org/docs/getting-started/cronos-testnet.html

But i can't seem to get the node to sync with the chain.
It starts to sync and just dies.

follow the tutorial and start the node
cronosd start

 - OS: Debian 11
 - Version: 0.6.6

```
2:49PM INF Unlocking keyring
2:49PM INF starting ABCI with Tendermint
2:49PM INF Starting multiAppConn service impl=multiAppConn module=proxy server=node
2:49PM INF Starting localClient service connection=query impl=localClient module=abci-client server=node
2:49PM INF Starting localClient service connection=snapshot impl=localClient module=abci-client server=node
2:49PM INF Starting localClient service connection=mempool impl=localClient module=abci-client server=node
2:49PM INF Starting localClient service connection=consensus impl=localClient module=abci-client server=node
2:49PM INF Starting EventBus service impl=EventBus module=events server=node
2:49PM INF Starting PubSub service impl=PubSub module=pubsub server=node
2:49PM INF Starting IndexerService service impl=IndexerService module=txindex server=node
2:49PM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 server=node software-version=0.6.6
2:49PM INF ABCI Replay Blocks appHeight=0 module=consensus server=node stateHeight=0 storeHeight=0
2:49PM INF asserting crisis invariants inv=0/11 module=x/crisis name=distribution/nonnegative-outstanding
2:49PM INF asserting crisis invariants inv=1/11 module=x/crisis name=distribution/can-withdraw
2:49PM INF asserting crisis invariants inv=2/11 module=x/crisis name=distribution/reference-count
2:49PM INF asserting crisis invariants inv=3/11 module=x/crisis name=distribution/module-account
2:49PM INF asserting crisis invariants inv=4/11 module=x/crisis name=staking/module-accounts
2:49PM INF asserting crisis invariants inv=5/11 module=x/crisis name=staking/nonnegative-power
2:49PM INF asserting crisis invariants inv=6/11 module=x/crisis name=staking/positive-delegation
2:49PM INF asserting crisis invariants inv=7/11 module=x/crisis name=staking/delegator-shares
2:49PM INF asserting crisis invariants inv=8/11 module=x/crisis name=bank/nonnegative-outstanding
2:49PM INF asserting crisis invariants inv=9/11 module=x/crisis name=bank/total-supply
2:49PM INF asserting crisis invariants inv=10/11 module=x/crisis name=gov/module-account
2:49PM INF asserted all invariants duration=4.401736 height=0 module=x/crisis
2:49PM INF created new capability module=ibc name=ports/transfer
2:49PM INF port binded module=x/ibc/port port=transfer
2:49PM INF claimed capability capability=1 module=transfer name=ports/transfer
2:49PM INF Completed ABCI Handshake - Tendermint and App are synced appHash= appHeight=0 module=consensus server=node
2:49PM INF Version info block=11 p2p=8 server=node tendermint_version=0.34.14
2:49PM INF This node is not a validator addr=4140A9EBEEAF8581E56F019A9012C86D98147B46 module=consensus pubKey=CtMqvf5q9VxTENDCrt+mR7wbeu4mh6JQvsBpHx9wGHk= server=node
2:49PM INF P2P Node ID ID=7fa2f73e8f8072237b98ce3a48ce45c93dc01a41 file=/home/cronos/.cronos/config/node_key.json module=p2p server=node
2:49PM INF Adding persistent peers addrs=["8fcba3485c67a2a00a383b6f45660a4ac529c6ca@52.77.30.18:26656","e65199bc579ffd89d7c021c5611f9f1c97f7ff13@54.251.209.254:26656"] module=p2p server=node
2:49PM INF Adding unconditional peer ids ids=[] module=p2p server=node
2:49PM INF Add our address to book addr={"id":"7fa2f73e8f8072237b98ce3a48ce45c93dc01a41","ip":"0.0.0.0","port":26656} book=/home/cronos/.cronos/config/addrbook.json module=p2p server=node
2:49PM INF Starting Node service impl=Node server=node
2:49PM INF Starting RPC HTTP server on 127.0.0.1:26657 module=rpc-server server=node
2:49PM INF Starting pprof server laddr=localhost:6060 server=node
2:49PM INF Starting P2P Switch service impl="P2P Switch" module=p2p server=node
2:49PM INF Starting Evidence service impl=Evidence module=evidence server=node
2:49PM INF Starting StateSync service impl=StateSync module=statesync server=node
2:49PM INF Starting PEX service impl=PEX module=pex server=node
2:49PM INF Starting AddrBook service book=/home/cronos/.cronos/config/addrbook.json impl=AddrBook module=p2p server=node
2:49PM INF Starting Mempool service impl=Mempool module=mempool server=node
2:49PM INF Starting BlockchainReactor service impl=BlockchainReactor module=blockchain server=node
2:49PM INF Starting BlockPool service impl=BlockPool module=blockchain server=node
2:49PM INF Starting Consensus service impl=ConsensusReactor module=consensus server=node
2:49PM INF Reactor  module=consensus server=node waitSync=true
2:49PM INF Saving AddrBook to file book=/home/cronos/.cronos/config/addrbook.json module=p2p server=node size=2
2:49PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=0 numToDial=10 server=node
2:49PM INF Will dial address addr={"id":"e65199bc579ffd89d7c021c5611f9f1c97f7ff13","ip":"54.251.209.254","port":26656} module=pex server=node
2:49PM INF Will dial address addr={"id":"8fcba3485c67a2a00a383b6f45660a4ac529c6ca","ip":"52.77.30.18","port":26656} module=pex server=node
2:49PM INF Dialing peer address={"id":"8fcba3485c67a2a00a383b6f45660a4ac529c6ca","ip":"52.77.30.18","port":26656} module=p2p server=node
2:49PM INF Dialing peer address={"id":"e65199bc579ffd89d7c021c5611f9f1c97f7ff13","ip":"54.251.209.254","port":26656} module=p2p server=node
2:49PM INF Starting Peer service impl="Peer{MConn{54.251.209.254:26656} e65199bc579ffd89d7c021c5611f9f1c97f7ff13 out}" module=p2p peer={"id":"e65199bc579ffd89d7c021c5611f9f1c97f7ff13","ip":"54.251.209.254","port":26656} server=node
2:49PM INF Starting MConnection service impl=MConn{54.251.209.254:26656} module=p2p peer={"id":"e65199bc579ffd89d7c021c5611f9f1c97f7ff13","ip":"54.251.209.254","port":26656} server=node
2:49PM INF Added peer module=p2p peer={"Data":{},"Logger":{}} server=node
2:49PM INF Starting Peer service impl="Peer{MConn{52.77.30.18:26656} 8fcba3485c67a2a00a383b6f45660a4ac529c6ca out}" module=p2p peer={"id":"8fcba3485c67a2a00a383b6f45660a4ac529c6ca","ip":"52.77.30.18","port":26656} server=node
2:49PM INF Starting MConnection service impl=MConn{52.77.30.18:26656} module=p2p peer={"id":"8fcba3485c67a2a00a383b6f45660a4ac529c6ca","ip":"52.77.30.18","port":26656} server=node
2:49PM INF Added peer module=p2p peer={"Data":{},"Logger":{}} server=node
2:49PM INF executed block height=1 module=state num_invalid_txs=0 num_valid_txs=0 server=node
2:49PM INF commit synced commit=436F6D6D697449447B5B3131322034352031393820332038392035342034362036312033203320313432203434203838203233352031303720313933203131382038372036382031313620313332203133392036302031323420343720313437203233382031312039312036392036203135355D3A317D
2:49PM INF committed state app_hash=702DC60359362E3D03038E2C58EB6BC176574474848B3C7C2F93EE0B5B45069B height=1 module=state num_txs=0 server=node
panic: Failed to process committed block (2:367D26D355C7D43AE671947EDC360E7C6E4DC60EAEA6D0754601E24A7A6CD901): wrong Block.Header.AppHash.  Expected 702DC60359362E3D03038E2C58EB6BC176574474848B3C7C2F93EE0B5B45069B, got 61BAA08C8C960B8873DAD2760E38DE73AC6DBBFC46A840DB435F20616AB570B5

goroutine 97 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc000d1ba40, 0x0)
        /go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/blockchain/v0/reactor.go:401 +0x1265
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
        /go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/blockchain/v0/reactor.go:110 +0x85
```
        
        

If i try to run it again i just get:
```
2:49PM INF Unlocking keyring
2:49PM INF starting ABCI with Tendermint
2:49PM INF Starting multiAppConn service impl=multiAppConn module=proxy server=node
2:49PM INF Starting localClient service connection=query impl=localClient module=abci-client server=node
2:49PM INF Starting localClient service connection=snapshot impl=localClient module=abci-client server=node
2:49PM INF Starting localClient service connection=mempool impl=localClient module=abci-client server=node
2:49PM INF Starting localClient service connection=consensus impl=localClient module=abci-client server=node
2:49PM INF Starting EventBus service impl=EventBus module=events server=node
2:49PM INF Starting PubSub service impl=PubSub module=pubsub server=node
2:49PM INF Starting IndexerService service impl=IndexerService module=txindex server=node
2:49PM INF ABCI Handshake App Info hash="p-�\x03Y6.=\x03\x03�,X�k�vWDt��<|/��\v[E\x06�" height=1 module=consensus protocol-version=0 server=node software-version=0.6.6
2:49PM INF ABCI Replay Blocks appHeight=1 module=consensus server=node stateHeight=1 storeHeight=2
2:49PM INF Replay last block using real app module=consensus server=node
2:49PM ERR failed init node error="error during handshake: error on replay: wrong Block.Header.AppHash.  Expected 702DC60359362E3D03038E2C58EB6BC176574474848B3C7C2F93EE0B5B45069B, got 61BAA08C8C960B8873DAD2760E38DE73AC6DBBFC46A840DB435F20616AB570B5"     
```

Unsafe reset does not help.
Any ideas on how to fix this?

**Comment by yihuang** [comment]
We just did a breaking upgrade on testnet, the simplest way may be to run a state-sync node:
1. download the binary from: https://github.com/crypto-org-chain/cronos/releases/tag/v0.7.0-rc2
2.
```
pip3 install pystarport
curl -o cronos-testnet-genesis.json https://raw.githubusercontent.com/crypto-org-chain/cronos-testnets/main/cronostestnet_338-3/genesis.json
cat > config.yaml << EOF
cronostestnet_338-3:
  cmd: cronosd
  validators:
    - name: fullnode
      config:
        statesync:
          enable: true
          rpc_servers: "https://cronos-testnet-3.crypto.org:26657,https://cronos-testnet-3.crypto.org:26657"
          trust_height: 1944002
          trust_hash: "5804B1883756AD4318D8AB5402327E64A6E3AEED2C8ABF7C573B3511CF377F88"
  genesis_file: "%(here)s/cronos-testnet-genesis.json"
  peers: "8fcba3485c67a2a00a383b6f45660a4ac529c6ca@52.77.30.18:26656,e65199bc579ffd89d7c021c5611f9f1c97f7ff13@54.251.209.254:26656"
EOF
pystarport serve
```

To run a normal synced node, you'll need cosmovisor stuff.

**Comment by yihuang** [comment]
you need to use https://github.com/crypto-org-chain/cronos/releases/tag/v0.6.0-testnet to sync from scratch.
but recently we upgraded testnet to `v0.7.0-rc2`, you'll need that version to sync the recent part of the chain.

**Comment by tkopicbeyondi** [comment]
Hello,

Thank you, i got version 0.6.0 to start but i also had to comment out: 
`tracer = ""`

in the app.toml to make it run. Otherwise it failed with this error:
`Error: invalid evm config value: invalid tracer type , available types: [json markdown struct access_list]: error in app.toml`

Seems to be fine now, It's catching up, now i just wait for it to sync and die to switch to 0.7.0-rc2

**Comment by yihuang** [comment]
> Hello,
> 
> Thank you, i got version 0.6.0 to start but i also had to comment out: `tracer = ""`
> 
> in the app.toml to make it run. Otherwise it failed with this error: `Error: invalid evm config value: invalid tracer type , available types: [json markdown struct access_list]: error in app.toml`
> 
> Seems to be fine now, It's catching up, now i just wait for it to sync and die to switch to 0.7.0-rc2

it's actually `0.6.0 -> 0.7.0-rc1 -> 0.7.0-rc2`, good luck.
