### ISSUE TITLE
using websocket to subscribe pending transaction closed in a short time

### ISSUE THREAD

**Issue by cryptocj** [crypto-org-chain/cronos#362]
**Describe the bug**
using WebSocket to subscribe pending transaction closed in a short time, and sometimes rerun the script can not connect to the server.

**To Reproduce**
1. setup a statesync mode mainnet node
2. run the following script
```javascript
var Web3 = require('web3');

var web3 = new Web3('ws://127.0.0.1:8546/');

subscription = web3.eth.subscribe('pendingTransactions', function (error, result) {})
    .on("data", function (transactionHash) {
        web3.eth.getTransaction(transactionHash)
        .then(function (transaction) {
            console.log(transactionHash);
        });
    })
```

Got these errors from the client
```shell
0x4c08424994f7cb8952cb092510e4f6ac1862ee425bb6d1146de420c9e782f62b
0x424784e57ec0401904357b04920f139cc7226eacfedff80458067ff5c594780e
0x0cebb0a33869f990675c7be04f9ca025e5ee9746544544efcb5bc12978763ce4
0x17903e9ba133928ff43b91cc5152a14ac2888e3bd17897ef522eb94b9794c32d
0x59766a4b719c107b56090899ad9538fa2b2a2fa854549d5421c408710fe1c6e6
0x3f6182420d0debc6e5be6a1138b1c3dc7a5059ec35e3078d37d48f33cbd25834
0xcb01abcc4f07eae7d81bd294649588867586e447afd346d8cf5ec0586fe3b6d7
0xad9dc6ce4c5d7ae2adf2aaff9eca17bc08fd3a0412b40f84dd5c6e6b95346dce
0x6b17cb3c8a72138d88daef7ace844a61d397943bc3a2b90f1317c90756622a4a
0x6a6b733636b4d49365690c3efc1c8887b3ea9a19b81fda6023dbafca77d5b6cf
0x192b7d2056f0134d8912f737b7aa5843a729a0017f3575f4d912a0d4627c6dd6
0x7d5b4ff9565e130fef4bf9384f415b4a35e5c63bd64925dc3691370f37e2b217
0x28474d4cf7a9912561facd6c1e38bb717f1ccc205da98142c99dc5c8c721429d
0x465bf6ed75298516ca0ecbe9b508fdede8cfa180420131d075f58d1f02a6924e
0xbdcafb6d61db088ed12dd2dd9f262663b402bf09c1856d16b464080c5c2453e9
0xe0b9ba51cd4524e7622bb7aade0408051bd1b4ee2431a1593fd12abad0547b0e
0x5ffaddf5bef4f6312c36b0315acf50cdc91a97948ea5e09cc5223dd06e6ac328
0x361f707cf81b57dbf82d13ffe2b9c1375e640dc83c5c126c464a9650a7bbeeee
0xc87873733c414afbb7693ac21c17f62e5624929c6680a307e28b67cc62292a90
0x1594022b5a93504dfa2482d341ee456c59bd83fe66ea4b5abb17a63c06916c2b
0x33b1903ad8ea24baed1578da79818916101823e7e7f67998a9b5043ff848cc5c
0x815fcf6e426807dc722d0a8e2c1aee2f001c60e4480026067caa1fe0268f2c3f
0x8698697a09678c982e0cea70a9ecaf28cc880dc0d5bd152002b182502cc0fa2a
0x87aa256e8046f6ac77cf14671b56b4865f2a927342f2a3c50339332a4e0ecc08
0x87f8610e964404d875b77e289859c4285a627a1cff404c9c946e7e7884b42e5f
/home/ubuntu/.Bot/pancake/node_modules/web3-core-helpers/lib/errors.js:66
        const error = new Error(msg);
                      ^

Error: CONNECTION ERROR: Couldn't connect to node on WS.
    at Object.ConnectionError (/home/ubuntu/.Bot/pancake/node_modules/web3-core-helpers/lib/errors.js:66:23)
    at Object.InvalidConnection (/home/ubuntu/.Bot/pancake/node_modules/web3-core-helpers/lib/errors.js:36:21)
    at /home/ubuntu/.Bot/pancake/node_modules/web3-providers-ws/lib/index.js:161:37
    at Map.forEach (<anonymous>)
    at WebsocketProvider._onClose (/home/ubuntu/.Bot/pancake/node_modules/web3-providers-ws/lib/index.js:160:28)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/ubuntu/.Bot/pancake/node_modules/yaeti/lib/EventTarget.js:115:12)
    at W3CWebSocket.onClose (/home/ubuntu/.Bot/pancake/node_modules/websocket/lib/W3CWebSocket.js:228:10)
    at WebSocketConnection.<anonymous> (/home/ubuntu/.Bot/pancake/node_modules/websocket/lib/W3CWebSocket.js:201:17)
    at WebSocketConnection.emit (node:events:520:28)
    at WebSocketConnection.handleSocketClose (/home/ubuntu/.Bot/pancake/node_modules/websocket/lib/WebSocketConnection.js:389:14)
    at Socket.emit (node:events:520:28)
    at TCP.<anonymous> (node:net:687:12) {
  code: 1006,
  reason: 'Socket Error: read ECONNRESET'
}
```

and found some node's error logs
```
t=2022-02-28T02:41:08+0000 lvl=dbug msg="Served eth_getTransactionByHash" conn=127.0.0.1:37714 reqid=2 t=4.824794ms
panic: debug

goroutine 2459 [running]:
github.com/tharsis/ethermint/rpc.(*pubSubAPI).subscribePendingTransactions.func1(0xc01367f440, 0xc0136b4360)
        /go/pkg/mod/github.com/crypto-org-chain/ethermint@v0.7.2-cronos-9/rpc/websockets.go:684 +0x80a
created by github.com/tharsis/ethermint/rpc.(*pubSubAPI).subscribePendingTransactions
        /go/pkg/mod/github.com/crypto-org-chain/ethermint@v0.7.2-cronos-9/rpc/websockets.go:676 +0x335
2:41AM INF Unlocking keyring
2:41AM INF starting ABCI with Tendermint
```

**Comment by yihuang** [comment]
closed by https://github.com/crypto-org-chain/cronos/pull/363
