### ISSUE TITLE
truffle Deployment Failed

### ISSUE THREAD

**Issue by milescui** [crypto-org-chain/cronos#421]
There is 17 CRO in my wallet, and GAS is enough.

```
 truffle migrate --network cronos --reset

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.



Starting migrations...
======================
> Network name:    'cronos'
> Network id:      25
> Block gas limit: 10000000 (0x989680)


1_initial_migration.js
======================

   Deploying 'Migrations'
   ----------------------

Error:  *** Deployment Failed ***

"Migrations" -- internal.

    at /usr/local/Cellar/truffle/5.4.9/libexec/lib/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:365:1
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Migration._deploy (/usr/local/Cellar/truffle/5.4.9/libexec/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:70:1)
    at Migration._load (/usr/local/Cellar/truffle/5.4.9/libexec/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:56:1)
    at Migration.run (/usr/local/Cellar/truffle/5.4.9/libexec/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:217:1)
    at Object.runMigrations (/usr/local/Cellar/truffle/5.4.9/libexec/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:150:1)
    at Object.runFrom (/usr/local/Cellar/truffle/5.4.9/libexec/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:110:1)
    at Object.runAll (/usr/local/Cellar/truffle/5.4.9/libexec/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:114:1)
    at Object.run (/usr/local/Cellar/truffle/5.4.9/libexec/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:79:1)
    at runMigrations (/usr/local/Cellar/truffle/5.4.9/libexec/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:258:1)
    at Object.run (/usr/local/Cellar/truffle/5.4.9/libexec/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:223:1)
    at Command.run (/usr/local/Cellar/truffle/5.4.9/libexec/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:172:1)
Truffle v5.4.9 (core: 5.4.9)
Node v16.13.0
```

truffle-config.js
```
 cronos: {
            provider: function() {
                return new HDWalletProvider([PRIVATE_KEY], 'https://evm.cronos.org');
            },
            network_id: '25',
            gas: 10000000,
            gasPrice: Web3.utils.toWei('5000', 'gwei'),
        },
```

**Comment by yihuang** [comment]
Could you find out what rpc query does it make that fails?

**Comment by milescui** [comment]
{ code: -32000, message: 'internal' }

**Comment by yihuang** [comment]
> { code: -32000, message: 'internal' }

I mean the full request, so I can reproduce myself.

**Comment by milescui** [comment]
Request Header
---
POST / HTTP/1.1
Accept: application/json
Content-Type: application/json
host: evm.cronos.org
content-length: 951
Connection: close

Request Body
---
```
{
  "id": 5615947998497439,
  "jsonrpc": "2.0",
  "method": "eth_sendRawTransaction",
  "params": [
    "0xf901ac0286048c27395000839896808080b90158608060405234801561001057600080fd5b50600080546001600160a01b03191633179055610126806100326000396000f3fe6080604052348015600f57600080fd5b5060043610603c5760003560e01c8063445df0ac1460415780638da5cb5b14605c578063fdacd57614609f575b600080fd5b604960015481565b6040519081526020015b60405180910390f35b600054607b9073ffffffffffffffffffffffffffffffffffffffff1681565b60405173ffffffffffffffffffffffffffffffffffffffff90911681526020016053565b60ae60aa36600460d8565b60b0565b005b60005473ffffffffffffffffffffffffffffffffffffffff1633141560d55760018190555b50565b60006020828403121560e957600080fd5b503591905056fea2646970667358221220a9033fb34806d44b4806f7c1944e694b40ff48a08bdb1391ef09da433f151b4d64736f6c6343000807003356a052b44cc2e7f151bb4f7f0af62e661e1508ed2aa0fcef61e44a298ca6ac8162b7a07305bf6fbaf600ffb938fc3c0a16bc99712fc71cfdc1af4d3879b5d28783f1c2"
  ]
}
```


Response Header
---
HTTP/1.1 200 OK
Date: Fri, 08 Apr 2022 09:04:16 GMT
Content-Type: application/json
Content-Length: 85
Connection: close
Set-Cookie: AWSALB=5R+Kh8MqmArM1qEMW/yzlZoy8mdlUYrDTeTH/qby2aOhpXLq3s897BNdx9xiuOSytWikX381iEfzP9Y8pyV8SM1zxc5+LGXn0CB2GalQDcLtNTzsQn7A3GybSLzB; Expires=Fri, 15 Apr 2022 09:04:16 GMT; Path=/
Vary: Origin
CF-Cache-Status: DYNAMIC
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Set-Cookie: AWSALBCORS=5R+Kh8MqmArM1qEMW/yzlZoy8mdlUYrDTeTH/qby2aOhpXLq3s897BNdx9xiuOSytWikX381iEfzP9Y8pyV8SM1zxc5+LGXn0CB2GalQDcLtNTzsQn7A3GybSLzB; Expires=Fri, 15 Apr 2022 09:04:16 GMT; Path=/; SameSite=None; Secure
Set-Cookie: __cf_bm=lNEIr7V4bh24zYW0EJTdORQ_Ngn7q5dJS5xx0aXqagU-1649408656-0-AYePP3s0d9zxKvONq8gA7OZGKxnvP22SINJpwmdpFJZM+T2bb//4HnemaRG+BaaEXC+pSo0Kelz5N6av6TMC+B8=; path=/; expires=Fri, 08-Apr-22 09:34:16 GMT; domain=.cronos.org; HttpOnly; Secure
Server: cloudflare
CF-RAY: 6f89d5a65bc723c8-HKG


Response Body
---
```
{
  "jsonrpc": "2.0",
  "id": 5615947998497439,
  "error": {
    "message": "internal",
    "code": -32000
  }
}
```

**Comment by milescui** [comment]
你好，你有微信或telegram吗？方便加下沟通吗？

**Comment by milescui** [comment]
```
 compilers: {
        solc: {
            version: '0.8.7', // Fetch exact version from solc-bin (default: truffle's version)
            settings: {
                optimizer: {
                    enabled: true,
                    runs: 2000,
                },
            },
        },
    },

**Comment by milescui** [comment]
我尝试了truffle很多版本都报同样的错误：5.5.7, 5.5.6, 5.4.9, 5.4.0, 5.1.61

**Comment by milescui** [comment]
比较奇怪的是，我用hardhat第一次部署成功了，但是，我没改配置和代码，部署第二次也报internal错误

第一次部署成功的：https://cronoscan.com/tx/0xa6bc57a1ded58e46e69a5f285d10fd44a447f4298f196a6f0420a64e29259c38

第二次失败的报错：
```
npx hardhat run scripts/deploy-cronos-token.js --network cronos

ProviderError: internal
    at HttpProvider.request (/Users/milescui/Downloads/cronos-smart-contract-example-master/hardhat/node_modules/hardhat/src/internal/core/providers/http.ts:49:19)
    at LocalAccountsProvider.request (/Users/milescui/Downloads/cronos-smart-contract-example-master/hardhat/node_modules/hardhat/src/internal/core/providers/accounts.ts:146:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at EthersProviderWrapper.send (/Users/milescui/Downloads/cronos-smart-contract-example-master/hardhat/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
```

**Comment by milescui** [comment]
我换了rpc地址，hardhat多试几次就能成功，truffle还是一直internal错误

**Comment by milescui** [comment]
问题已解决，是我gas不够导致的，谢谢
