### ISSUE TITLE
Failed to run v0.7.1-rc2(UPGRADE "v0.7.0-hotfix" NEEDED at height: 3982500)

### ISSUE THREAD

**Issue by jsvisa** [crypto-org-chain/cronos#614]
**Describe the bug**

I'm downloading the latest [v0.7.1-rc2 release](https://github.com/crypto-org-chain/cronos/releases/tag/v0.7.1-rc2), and upgrade from 0.7.1-rc1, but failed to run the node, panic log as below:

```
Hint: You are currently not seeing messages from other users and the system.
      Users in groups 'adm', 'systemd-journal', 'wheel' can see all messages.
      Pass -q to turn off this notice.
-- Logs begin at Wed 2022-07-20 04:45:50 UTC. --
Aug 03 04:36:35 ip-10-132-83-109.ap-southeast-1.compute.internal cronosd[36149]: panic: UPGRADE "v0.7.0-hotfix" NEEDED at height: 3982500: {"binaries":{"darwin/amd64":"https://github.com/crypto-org-chain/cronos/releases/download/v0.7.0-hotfix/cronos_0.7.0-hotfix_Darwin_x86_64.tar.gz?checksum=sha256:ad57deb8f5f2106cc7f5af5e3d8cd6aa28c308ef7e32c6db64492f5500d6cc6f","darwin/arm64":"https://github.com/crypto-org-chain/cronos/releases/download/v0.7.0-hotfix/cronos_0.7.0-hotfix_Darwin_arm64.tar.gz?checksum=sha256:76cad388ebcfc84e140dcc1d8933b863636f5fad67f8783747b02fab6e69f305","linux/amd64":"https://github.com/crypto-org-chain/cronos/releases/download/v0.7.0-hotfix/cronos_0.7.0-hotfix_Linux_x86_64.tar.gz?checksum=sha256:48419d7c33aaed82c0e78ded39e97f9a14563e4d3037a1342cf617ae6d3a1837","linux/arm64":"https://github.com/crypto-org-chain/cronos/releases/download/v0.7.0-hotfix/cronos_0.7.0-hotfix_Linux_arm64.tar.gz?checksum=sha256:3c9682aa7ab0522c01f7d1e92f645ccc6ee9a831a611eb24a362ccdecbc71abc","windows/amd64":"https://github.com/crypto-org-chain/cronos/releases/download/v0.7.0-hotfix/cronos_0.7.0-hotfix_Windows_x86_64.zip?checksum=sha256:10c732d1c4e4341ccbc22e4744fc2048c13229be1dc2740dfd02058a47d4a4d0"}}
Aug 03 04:36:35 ip-10-132-83-109.ap-southeast-1.compute.internal cronosd[36149]: goroutine 1 [running]:
Aug 03 04:36:35 ip-10-132-83-109.ap-southeast-1.compute.internal cronosd[36149]: github.com/cosmos/cosmos-sdk/x/upgrade.BeginBlocker({{0x7fff7ac3df47, 0xb}, 0xc013448180, {0x2d9d398, 0xc013442e60}, {0x2e01b58, 0xc001435640}, 0xc013449980, {0x2d8b460, 0xc001f01860}, ...}, ...)
Aug 03 04:36:35 ip-10-132-83-109.ap-southeast-1.compute.internal cronosd[36149]: /home/amber/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/x/upgrade/abci.go:71 +0x101f
Aug 03 04:36:35 ip-10-132-83-109.ap-southeast-1.compute.internal cronosd[36149]: github.com/cosmos/cosmos-sdk/x/upgrade.AppModule.BeginBlock(...)
Aug 03 04:36:35 ip-10-132-83-109.ap-southeast-1.compute.internal cronosd[36149]: /home/amber/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/x/upgrade/module.go:130
Aug 03 04:36:35 ip-10-132-83-109.ap-southeast-1.compute.internal cronosd[36601]: 4:36AM INF Unlocking keyring
Aug 03 04:36:35 ip-10-132-83-109.ap-southeast-1.compute.internal cronosd[36601]: 4:36AM INF starting ABCI with Tendermint
Aug 03 04:36:54 ip-10-132-83-109.ap-southeast-1.compute.internal cronosd[36776]: 4:36AM INF Unlocking keyring
Aug 03 04:36:54 ip-10-132-83-109.ap-southeast-1.compute.internal cronosd[36776]: 4:36AM INF starting ABCI with Tendermint

```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by yihuang** [comment]
Can you post the output of:
```
./cronosd version --long
```

**Comment by jsvisa** [comment]
```
name: cronos
server_name: cronosd
version: v0.7.0-hotfix
commit: b918149
build_tags: ledger,cgo,mainnet,rocksdb
go: go version go1.17.5 linux/amd64
build_deps:
- '@(devel)'
cosmos_sdk_version: ""
```

**Comment by dandavid3000** [comment]
Hello,

I'm syncing cronos using snapshot cronosmainnet_25-1-pruned.20220801.2010.tar.lz4 with cronosd 0.7.0 and I'm having the same issue


```7:24AM INF Unlocking keyring
7:24AM INF starting ABCI with Tendermint
7:24AM INF Starting multiAppConn service impl=multiAppConn module=proxy server=node
7:24AM INF Starting localClient service connection=query impl=localClient module=abci-client server=node
7:24AM INF Starting localClient service connection=snapshot impl=localClient module=abci-client server=node
7:24AM INF Starting localClient service connection=mempool impl=localClient module=abci-client server=node
7:24AM INF Starting localClient service connection=consensus impl=localClient module=abci-client server=node
7:24AM INF Starting EventBus service impl=EventBus module=events server=node
7:24AM INF Starting PubSub service impl=PubSub module=pubsub server=node
7:24AM INF Starting IndexerService service impl=IndexerService module=txindex server=node
7:24AM INF ABCI Handshake App Info hash="��o�\x14D�?�����2\x19�J��N��]��\x18A�\x019T�" height=3982499 module=consensus protocol-version=0 server=node software-version=0.7.0
7:24AM INF ABCI Replay Blocks appHeight=3982499 module=consensus server=node stateHeight=3982499 storeHeight=3982500
7:24AM INF Replay last block using real app module=consensus server=node
7:24AM ERR UPGRADE "v0.7.0-hotfix" NEEDED at height: 3982500: {"binaries":{"darwin/amd64":"https://github.com/crypto-org-chain/cronos/releases/download/v0.7.0-hotfix/cronos_0.7.0-hotfix_Darwin_x86_64.tar.gz?checksum=sha256:ad57deb8f5f2106cc7f5af5e3d8cd6aa28c308ef7e32c6db64492f5500d6cc6f","darwin/arm64":"https://github.com/crypto-org-chain/cronos/releases/download/v0.7.0-hotfix/cronos_0.7.0-hotfix_Darwin_arm64.tar.gz?checksum=sha256:76cad388ebcfc84e140dcc1d8933b863636f5fad67f8783747b02fab6e69f305","linux/amd64":"https://github.com/crypto-org-chain/cronos/releases/download/v0.7.0-hotfix/cronos_0.7.0-hotfix_Linux_x86_64.tar.gz?checksum=sha256:48419d7c33aaed82c0e78ded39e97f9a14563e4d3037a1342cf617ae6d3a1837","linux/arm64":"https://github.com/crypto-org-chain/cronos/releases/download/v0.7.0-hotfix/cronos_0.7.0-hotfix_Linux_arm64.tar.gz?checksum=sha256:3c9682aa7ab0522c01f7d1e92f645ccc6ee9a831a611eb24a362ccdecbc71abc","windows/amd64":"https://github.com/crypto-org-chain/cronos/releases/download/v0.7.0-hotfix/cronos_0.7.0-hotfix_Windows_x86_64.zip?checksum=sha256:10c732d1c4e4341ccbc22e4744fc2048c13229be1dc2740dfd02058a47d4a4d0"}}
panic: UPGRADE "v0.7.0-hotfix" NEEDED at height: 3982500: {"binaries":{"darwin/amd64":"https://github.com/crypto-org-chain/cronos/releases/download/v0.7.0-hotfix/cronos_0.7.0-hotfix_Darwin_x86_64.tar.gz?checksum=sha256:ad57deb8f5f2106cc7f5af5e3d8cd6aa28c308ef7e32c6db64492f5500d6cc6f","darwin/arm64":"https://github.com/crypto-org-chain/cronos/releases/download/v0.7.0-hotfix/cronos_0.7.0-hotfix_Darwin_arm64.tar.gz?checksum=sha256:76cad388ebcfc84e140dcc1d8933b863636f5fad67f8783747b02fab6e69f305","linux/amd64":"https://github.com/crypto-org-chain/cronos/releases/download/v0.7.0-hotfix/cronos_0.7.0-hotfix_Linux_x86_64.tar.gz?checksum=sha256:48419d7c33aaed82c0e78ded39e97f9a14563e4d3037a1342cf617ae6d3a1837","linux/arm64":"https://github.com/crypto-org-chain/cronos/releases/download/v0.7.0-hotfix/cronos_0.7.0-hotfix_Linux_arm64.tar.gz?checksum=sha256:3c9682aa7ab0522c01f7d1e92f645ccc6ee9a831a611eb24a362ccdecbc71abc","windows/amd64":"https://github.com/crypto-org-chain/cronos/releases/download/v0.7.0-hotfix/cronos_0.7.0-hotfix_Windows_x86_64.zip?checksum=sha256:10c732d1c4e4341ccbc22e4744fc2048c13229be1dc2740dfd02058a47d4a4d0"}}

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/upgrade.BeginBlocker({{0x7fffb6a16214, 0x2a}, 0xc0025ce1e0, {0x2dae238, 0xc002c82470}, {0x2e12c98, 0xc00145bca0}, 0xc002428bd0, {0x2d9c240, 0xc001f9a680}, ...}, ...)
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/x/upgrade/abci.go:71 +0x101f
github.com/cosmos/cosmos-sdk/x/upgrade.AppModule.BeginBlock(...)
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/x/upgrade/module.go:130
github.com/cosmos/cosmos-sdk/types/module.(*Manager).BeginBlock(_, {{0x2de7528, 0xc00019e000}, {0x2e18c20, 0xc003c61400}, {{0xb, 0x0}, {0xc003be5380, 0x12}, 0x3cc4a4, ...}, ...}, ...)
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/types/module/module.go:479 +0x218
github.com/crypto-org-chain/cronos/app.(*App).BeginBlocker(...)
	/go/src/github.com/crypto-org-chain/cronos/app/app.go:762
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).BeginBlock(_, {{0xc0055c5900, 0x20, 0x20}, {{0xb, 0x0}, {0xc003be5380, 0x12}, 0x3cc4a4, {0x1ceddc5c, ...}, ...}, ...})
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/baseapp/abci.go:194 +0x9dc
github.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(_, {{0xc0055c5900, 0x20, 0x20}, {{0xb, 0x0}, {0xc003be5380, 0x12}, 0x3cc4a4, {0x1ceddc5c, ...}, ...}, ...})
	/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/abci/client/local_client.go:280 +0x118
github.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(_, {{0xc0055c5900, 0x20, 0x20}, {{0xb, 0x0}, {0xc003be5380, 0x12}, 0x3cc4a4, {0x1ceddc5c, ...}, ...}, ...})
	/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/proxy/app_conn.go:81 +0x55
github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x2de8408, 0xc001239a40}, {0x2dffd40, 0xc004a946a0}, 0xc00000d2c0, {0x2e136a8, 0xc004a538c0}, 0x3cc4a3)
	/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/state/execution.go:307 +0x3dd
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc004a58970, 0x7}}, {0xc003be48a0, 0x12}, 0x1, 0x3cc4a3, {{0xc00309a120, ...}, ...}, ...}, ...)
	/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/state/execution.go:140 +0x171
github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlock(_, {{{0xb, 0x0}, {0xc004a58970, 0x7}}, {0xc003be48a0, 0x12}, 0x1, 0x3cc4a3, {{0xc00309a120, ...}, ...}, ...}, ...)
	/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:503 +0x23c
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0xc004a58970, 0x7}}, {0xc003be48a0, 0x12}, 0x1, 0x3cc4a3, {{0xc00309a120, ...}, ...}, ...}, ...)
	/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:416 +0x7ae
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc00587d8a0, {0x2e1a4b8, 0xc001234820})
	/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:268 +0x3c8
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0xc004a58970, 0x7}}, {0xc003be48a0, 0x12}, 0x1, 0x3cc4a3, ...}, ...)
	/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/node/node.go:325 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc0005c8500, {0x2dbef50, 0xc0005ff360}, 0xc002664900, {0x2d9d500, 0xc005a24fa8}, 0x0, 0x0, 0xc002664a60, {0x2de8408, ...}, ...)
	/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/node/node.go:733 +0x578
github.com/tharsis/ethermint/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x2e2df78, 0xc000f5e150}, {0x0, 0x0}, {0x2df1648, 0xc00145bca0}, ...}, ...)
	/go/pkg/mod/github.com/crypto-org-chain/ethermint@v0.10.0-alpha1-cronos-9/server/start.go:302 +0xc9f
github.com/tharsis/ethermint/server.StartCmd.func2(0xc00134cf00, {0xc0002a6620, 0x0, 0x2})
	/go/pkg/mod/github.com/crypto-org-chain/ethermint@v0.10.0-alpha1-cronos-9/server/start.go:117 +0x228
github.com/spf13/cobra.(*Command).execute(0xc00134cf00, {0xc0002a6600, 0x2, 0x2})
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc000328280)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:895
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0, {0xc0014665d0, 0x11})
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/server/cmd/execute.go:36 +0x1eb
main.main()
	/go/src/github.com/crypto-org-chain/cronos/cmd/cronosd/main.go:13 +0x2c
```


```
./cronosd version --long
name: cronos
server_name: cronosd
version: 0.7.0
commit: 799ac47e293403bd57580d2ff96bb8d9851c3cde
build_tags: ""
go: go version go1.17.9 linux/amd64
build_deps:
- filippo.io/edwards25519@v1.0.0-beta.2
- github.com/99designs/keyring@v1.1.6 => github.com/crypto-org-chain/keyring@v1.1.6-fixes
- github.com/ChainSafe/go-schnorrkel@v0.0.0-20200405005733-88cbf1b4c40d
- github.com/VictoriaMetrics/fastcache@v1.6.0
- github.com/Workiva/go-datastructures@v1.0.53
- github.com/armon/go-metrics@v0.3.10
- github.com/beorn7/perks@v1.0.1
- github.com/bgentry/speakeasy@v0.1.0
- github.com/btcsuite/btcd@v0.22.0-beta
- github.com/btcsuite/btcutil@v1.0.3-0.20201208143702-a53e38424cce
- github.com/cenkalti/backoff/v4@v4.1.1
- github.com/cespare/xxhash/v2@v2.1.2
- github.com/coinbase/rosetta-sdk-go@v0.7.0
- github.com/confio/ics23/go@v0.7.0
- github.com/cosmos/btcutil@v1.0.4
- github.com/cosmos/cosmos-sdk@v0.45.4 => github.com/cosmos/cosmos-sdk@v0.45.4
- github.com/cosmos/go-bip39@v1.0.0
- github.com/cosmos/iavl@v0.17.3
- github.com/cosmos/ibc-go/v2@v2.2.0 => github.com/crypto-org-chain/ibc-go/v2@v2.2.0-hooks2
- github.com/cosmos/ledger-cosmos-go@v0.11.1
- github.com/cosmos/ledger-go@v0.9.2
- github.com/davecgh/go-spew@v1.1.1
- github.com/deckarep/golang-set@v0.0.0-20180603214616-504e848d77ea
- github.com/desertbit/timer@v0.0.0-20180107155436-c41aec40b27f
- github.com/dvsekhvalnov/jose2go@v0.0.0-20200901110807-248326c1351b
- github.com/edsrzf/mmap-go@v1.0.0
- github.com/ethereum/go-ethereum@v1.10.15
- github.com/felixge/httpsnoop@v1.0.1
- github.com/fsnotify/fsnotify@v1.5.1
- github.com/gballet/go-libpcsclite@v0.0.0-20190607065134-2772fd86a8ff
- github.com/go-kit/kit@v0.12.0
- github.com/go-kit/log@v0.2.0
- github.com/go-logfmt/logfmt@v0.5.1
- github.com/go-stack/stack@v1.8.0
- github.com/godbus/dbus@v0.0.0-20190726142602-4481cbc300e2
- github.com/gogo/gateway@v1.1.0
- github.com/gogo/protobuf@v1.3.3 => github.com/regen-network/protobuf@v1.3.3-alpha.regen.1
- github.com/golang/protobuf@v1.5.2
- github.com/golang/snappy@v0.0.4
- github.com/google/btree@v1.0.1
- github.com/google/orderedcode@v0.0.1
- github.com/google/uuid@v1.3.0
- github.com/gorilla/handlers@v1.5.1
- github.com/gorilla/mux@v1.8.0
- github.com/gorilla/websocket@v1.5.0
- github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0
- github.com/grpc-ecosystem/grpc-gateway@v1.16.0
- github.com/gsterjov/go-libsecret@v0.0.0-20161001094733-a6f4afe4910c
- github.com/gtank/merlin@v0.1.1
- github.com/gtank/ristretto255@v0.1.2
- github.com/hashicorp/go-immutable-radix@v1.3.1
- github.com/hashicorp/golang-lru@v0.5.5-0.20210104140557-80c98217689d
- github.com/hashicorp/hcl@v1.0.0
- github.com/hdevalence/ed25519consensus@v0.0.0-20210204194344-59a8610d2b87
- github.com/holiman/bloomfilter/v2@v2.0.3
- github.com/holiman/uint256@v1.2.0
- github.com/huin/goupnp@v1.0.2
- github.com/improbable-eng/grpc-web@v0.15.0
- github.com/jackpal/go-nat-pmp@v1.0.2-0.20160603034137-1fa385a6f458
- github.com/klauspost/compress@v1.13.6
- github.com/lib/pq@v1.10.4
- github.com/libp2p/go-buffer-pool@v0.0.2
- github.com/magiconair/properties@v1.8.6
- github.com/mattn/go-isatty@v0.0.14
- github.com/mattn/go-runewidth@v0.0.9
- github.com/matttproud/golang_protobuf_extensions@v1.0.1
- github.com/mimoo/StrobeGo@v0.0.0-20181016162300-f8f6d4d2b643
- github.com/minio/highwayhash@v1.0.2
- github.com/mitchellh/mapstructure@v1.4.3
- github.com/mtibben/percent@v0.2.1
- github.com/olekukonko/tablewriter@v0.0.5
- github.com/peggyjv/gravity-bridge/module@v0.3.9
- github.com/pelletier/go-toml@v1.9.4
- github.com/pkg/errors@v0.9.1
- github.com/pmezard/go-difflib@v1.0.0
- github.com/prometheus/client_golang@v1.12.1
- github.com/prometheus/client_model@v0.2.0
- github.com/prometheus/common@v0.32.1
- github.com/prometheus/procfs@v0.7.3
- github.com/prometheus/tsdb@v0.7.1
- github.com/rakyll/statik@v0.1.7
- github.com/rcrowley/go-metrics@v0.0.0-20201227073835-cf1acfcdf475
- github.com/regen-network/cosmos-proto@v0.3.1
- github.com/rjeczalik/notify@v0.9.1
- github.com/rs/cors@v1.8.2
- github.com/rs/zerolog@v1.26.0
- github.com/shirou/gopsutil@v3.21.4-0.20210419000835-c7a38de76ee5+incompatible
- github.com/spf13/afero@v1.8.2
- github.com/spf13/cast@v1.4.1
- github.com/spf13/cobra@v1.4.0
- github.com/spf13/jwalterweatherman@v1.1.0
- github.com/spf13/pflag@v1.0.5
- github.com/spf13/viper@v1.11.0
- github.com/status-im/keycard-go@v0.0.0-20200402102358-957c09536969
- github.com/stretchr/testify@v1.7.1
- github.com/subosito/gotenv@v1.2.0
- github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7
- github.com/tendermint/btcd@v0.1.1
- github.com/tendermint/crypto@v0.0.0-20191022145703-50d29ede1e15
- github.com/tendermint/go-amino@v0.16.0
- github.com/tendermint/tendermint@v0.34.19
- github.com/tendermint/tm-db@v0.6.7
- github.com/tharsis/ethermint@v0.10.0-alpha1 => github.com/crypto-org-chain/ethermint@v0.10.0-alpha1-cronos-9
- github.com/tklauser/go-sysconf@v0.3.7
- github.com/tklauser/numcpus@v0.2.3
- github.com/tyler-smith/go-bip39@v1.1.0
- github.com/zondax/hid@v0.9.0
- golang.org/x/crypto@v0.0.0-20220411220226-7b82a4e95df4
- golang.org/x/net@v0.0.0-20220412020605-290c469a71a5
- golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c
- golang.org/x/sys@v0.0.0-20220412211240-33da011f77ad
- golang.org/x/term@v0.0.0-20210927222741-03fcf44c2211
- golang.org/x/text@v0.3.7
- google.golang.org/genproto@v0.0.0-20220407144326-9054f6ed7bac
- google.golang.org/grpc@v1.45.0 => google.golang.org/grpc@v1.33.2
- google.golang.org/protobuf@v1.28.0
- gopkg.in/ini.v1@v1.66.4
- gopkg.in/olebedev/go-duktape.v3@v3.0.0-20200619000410-60c24ae608a6
- gopkg.in/yaml.v2@v2.4.0
- gopkg.in/yaml.v3@v3.0.0-20210107192922-496545a6307b
- nhooyr.io/websocket@v1.8.6
cosmos_sdk_version: v0.45.4
```

**Comment by yihuang** [comment]
@dandavid3000 your version is not the hotfix binary we released, notice that the source code patch is not disclosed yet, so you can't built it from source code yet.

**Comment by yihuang** [comment]
> ```
> name: cronos
> server_name: cronosd
> version: v0.7.0-hotfix
> commit: b918149
> build_tags: ledger,cgo,mainnet,rocksdb
> go: go version go1.17.5 linux/amd64
> build_deps:
> - '@(devel)'
> cosmos_sdk_version: ""
> ```

this is the `v0.7.0-hotfix`, but it should be fine, there are many nodes using it. can you double-check if the node actually runs with the correct binary?

**Comment by dandavid3000** [comment]
> @dandavid3000 your version is not the hotfix binary we released, notice that the source code patch is not disclosed yet, so you can't build it from the source code yet. must download from https://github.com/crypto-org-chain/cronos/releases/tag/v0.7.1-rc2

Thank you. I downloaded v0.7.0-hotfix and it seems OK. I tried with 0.7.1-rc2 but it did not work. It said I'm missing some libs. IDK if I need to install something else ?

**Comment by jsvisa** [comment]
> 

You can download the rocksdb's release

**Comment by jsvisa** [comment]
> > ```
> > name: cronos
> > server_name: cronosd
> > version: v0.7.0-hotfix
> > commit: b918149
> > build_tags: ledger,cgo,mainnet,rocksdb
> > go: go version go1.17.5 linux/amd64
> > build_deps:
> > - '@(devel)'
> > cosmos_sdk_version: ""
> > ```
> 
> this is the `v0.7.0-hotfix`, but it should be fine too, there are many nodes using it. can you double-check if the node actually runs with the correct binary?

I'll take another look.

**Comment by jsvisa** [comment]
> > @dandavid3000 your version is not the hotfix binary we released, notice that the source code patch is not disclosed yet, so you can't build it from the source code yet. must download from https://github.com/crypto-org-chain/cronos/releases/tag/v0.7.1-rc2
> 
> Thank you. I downloaded v0.7.0-hotfix and it seems OK. I tried with 0.7.1-rc2 but it did not work. It said I'm missing some libs. IDK if I need to install something else ?

You can download the rocksdb's release https://github.com/crypto-org-chain/cronos/releases/download/v0.7.1-rc2/cronos_0.7.1-rc2-rocksdb_Linux_x86_64.tar.gz

**Comment by jsvisa** [comment]
@yihuang I meet another issue:

```
6:08AM ERR failed to open DB error="failed to initialize database: Corruption: VersionBuilder: Cannot add table file #714017748 to level 0 since it is already in the LSM tree on level 0"
Error: failed to initialize database: Corruption: VersionBuilder: Cannot add table file #714017748 to level 0 since it is already in the LSM tree on level 0
```

**Comment by yihuang** [comment]
> @yihuang I meet another issue:
> 
> ```
> 6:08AM ERR failed to open DB error="failed to initialize database: Corruption: VersionBuilder: Cannot add table file #714017748 to level 0 since it is already in the LSM tree on level 0"
> Error: failed to initialize database: Corruption: VersionBuilder: Cannot add table file #714017748 to level 0 since it is already in the LSM tree on level 0
> ```

I think either the db files are indeed corrupted, or you mixup rocksdb and goleveldb binaries.

**Comment by yihuang** [comment]
> > @dandavid3000 your version is not the hotfix binary we released, notice that the source code patch is not disclosed yet, so you can't build it from the source code yet. must download from https://github.com/crypto-org-chain/cronos/releases/tag/v0.7.1-rc2
> 
> Thank you. I downloaded v0.7.0-hotfix and it seems OK. I tried with 0.7.1-rc2 but it did not work. It said I'm missing some libs. IDK if I need to install something else ?

which platform do you use, and what error messages do you see?

**Comment by jsvisa** [comment]
> > @yihuang I meet another issue:
> > ```
> > 6:08AM ERR failed to open DB error="failed to initialize database: Corruption: VersionBuilder: Cannot add table file #714017748 to level 0 since it is already in the LSM tree on level 0"
> > Error: failed to initialize database: Corruption: VersionBuilder: Cannot add table file #714017748 to level 0 since it is already in the LSM tree on level 0
> > ```
> 
> I think either the db files are indeed corrupted, or you mixup rocksdb and goleveldb binaries.

Thanks for your explanation, my problem is solved.

**Comment by dandavid3000** [comment]
> > > @dandavid3000 your version is not the hotfix binary we released, notice that the source code patch is not disclosed yet, so you can't build it from the source code yet. must download from https://github.com/crypto-org-chain/cronos/releases/tag/v0.7.1-rc2
> > 
> > 
> > Thank you. I downloaded v0.7.0-hotfix and it seems OK. I tried with 0.7.1-rc2 but it did not work. It said I'm missing some libs. IDK if I need to install something else ?
> 
> which platform do you use, and what error messages do you see?

I'm using ubuntu 20.04

```./cronosd: 4: exec: /cronos_0.7.1-rc2_Linux_x86_64/bin/lib/ld-linux-x86-64.so.2: not found```

This package seems weird for me: cronos_0.7.1-rc2_Linux_x86_64.tar.gz
```
$ tree .
.
├── bin
│   └── cronosd
├── exe
│   └── cronosd
└── lib
    ├── ld-2.33.so
    ├── ld-linux-x86-64.so.2 -> ld-2.33.so
    ├── libc-2.33.so
    ├── libc.so.6 -> libc-2.33.so
    ├── libm-2.33.so
    ├── libm.so.6 -> libm-2.33.so
    ├── libpthread-2.33.so
    ├── libpthread.so.0 -> libpthread-2.33.so
    ├── librt-2.33.so
    └── librt.so.1 -> librt-2.33.so```

**Comment by yihuang** [comment]
@dandavid3000 you should keep the directory structure, and run the `./bin/cronosd`, you shouldn't move the `bin/cronosd` file out of it.

**Comment by dandavid3000** [comment]
> @dandavid3000 you need to keep the directory structure, and run the `./bin/cronosd`, you shouldn't move the `bin/cronosd` file out of it, it'll find the dependencies by relative directory.

Thanks. That works
