### ISSUE TITLE
Cannot sync with cronos v0.8.2

### ISSUE THREAD

**Issue by dandavid3000** [crypto-org-chain/cronos#744]
Hi,

I upgraded cronos from v0.8.1 to v0.8.2. After running for a half of day, the node did not sync anymore. I stopped the node and restarted it. It showed me these errors below. What should I do ?

```
5:20PM INF Unlocking keyring
5:20PM INF starting ABCI with Tendermint
5:21PM INF service start impl=multiAppConn module=proxy msg={} server=node
5:21PM INF service start connection=query impl=localClient module=abci-client msg={} server=node
5:21PM INF service start connection=snapshot impl=localClient module=abci-client msg={} server=node
5:21PM INF service start connection=mempool impl=localClient module=abci-client msg={} server=node
5:21PM INF service start connection=consensus impl=localClient module=abci-client msg={} server=node
5:21PM INF service start impl=EventBus module=events msg={} server=node
5:21PM INF service start impl=PubSub module=pubsub msg={} server=node
5:21PM INF service start impl=IndexerService module=txindex msg={} server=node
5:21PM INF ABCI Handshake App Info hash="oIg:\x18\x0e��\x02A#mG]!�\x01��'1�gԄ;���\x13\x05�" height=5176497 module=consensus protocol-version=0 server=node software-version=v0.8.0
5:21PM INF ABCI Replay Blocks appHeight=5176497 module=consensus server=node stateHeight=5176497 storeHeight=5176498
5:21PM INF Replay last block using real app module=consensus server=node
5:21PM INF minted coins from module account amount=193042800000000000000000basecro from=evm module=x/bank
5:21PM INF burned tokens from module account amount=193042800000000000000000basecro from=evm module=x/bank
5:21PM INF executed block height=5176498 module=consensus num_invalid_txs=0 num_valid_txs=6 server=node
panic: version 5176498 was already saved to different hash 0395791E66F2111646D4753D9FE6C7E031BA488D95F3208080B39FE1AB6920AE (existing hash CBBAD9349BBA56E20E18148DD625A2CFADCE7E099DDE5D6E45784CAAD908A417)

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/store/iavl.(*Store).Commit(0xc0049d66b0)
	/build/8j4z3vqpxwq9r45xzyj4hj30h1kj55sj-source/vendor/github.com/cosmos/cosmos-sdk/store/iavl/store.go:132 +0xea
github.com/cosmos/cosmos-sdk/store/rootmulti.commitStores(0x4efcb2, 0xc0068f7b60)
	/build/8j4z3vqpxwq9r45xzyj4hj30h1kj55sj-source/vendor/github.com/cosmos/cosmos-sdk/store/rootmulti/store.go:970 +0x150
github.com/cosmos/cosmos-sdk/store/rootmulti.(*Store).Commit(0xc0002b1d40)
	/build/8j4z3vqpxwq9r45xzyj4hj30h1kj55sj-source/vendor/github.com/cosmos/cosmos-sdk/store/rootmulti/store.go:411 +0x72
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Commit(0xc001026700)
	/build/8j4z3vqpxwq9r45xzyj4hj30h1kj55sj-source/vendor/github.com/cosmos/cosmos-sdk/baseapp/abci.go:314 +0x1e9
github.com/tendermint/tendermint/abci/client.(*localClient).CommitSync(0xc00151fd40)
	/build/8j4z3vqpxwq9r45xzyj4hj30h1kj55sj-source/vendor/github.com/tendermint/tendermint/abci/client/local_client.go:264 +0xb6
github.com/tendermint/tendermint/proxy.(*appConnConsensus).CommitSync(0x50?)
	/build/8j4z3vqpxwq9r45xzyj4hj30h1kj55sj-source/vendor/github.com/tendermint/tendermint/proxy/app_conn.go:93 +0x22
github.com/tendermint/tendermint/state.(*BlockExecutor).Commit(_, {{{0xb, 0x0}, {0xc004b6aef0, 0x7}}, {0xc00a5ffd70, 0x12}, 0x1, 0x4efcb2, {{0xc01430d740, ...}, ...}, ...}, ...)
	/build/8j4z3vqpxwq9r45xzyj4hj30h1kj55sj-source/vendor/github.com/tendermint/tendermint/state/execution.go:228 +0x269
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc004b6aef0, 0x7}}, {0xc00a5ffd70, 0x12}, 0x1, 0x4efcb2, {{0xc01430d740, ...}, ...}, ...}, ...)
	/build/8j4z3vqpxwq9r45xzyj4hj30h1kj55sj-source/vendor/github.com/tendermint/tendermint/state/execution.go:180 +0x6ee
github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlock(_, {{{0xb, 0x0}, {0xc004b6aef0, 0x7}}, {0xc00a5ffd70, 0x12}, 0x1, 0x4efcb1, {{0xc001f959a0, ...}, ...}, ...}, ...)
	/build/8j4z3vqpxwq9r45xzyj4hj30h1kj55sj-source/vendor/github.com/tendermint/tendermint/consensus/replay.go:503 +0x23c
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0xc004b6aef0, 0x7}}, {0xc00a5ffd70, 0x12}, 0x1, 0x4efcb1, {{0xc001f959a0, ...}, ...}, ...}, ...)
	/build/8j4z3vqpxwq9r45xzyj4hj30h1kj55sj-source/vendor/github.com/tendermint/tendermint/consensus/replay.go:416 +0x7ae
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc01d01d880, {0x2e24b60, 0xc0014884e0})
	/build/8j4z3vqpxwq9r45xzyj4hj30h1kj55sj-source/vendor/github.com/tendermint/tendermint/consensus/replay.go:268 +0x3c8
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0xc004b6aef0, 0x7}}, {0xc00a5ffd70, 0x12}, 0x1, 0x4efcb1, ...}, ...)
	/build/8j4z3vqpxwq9r45xzyj4hj30h1kj55sj-source/vendor/github.com/tendermint/tendermint/node/node.go:328 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc0002caf00, {0x2e11bd8, 0xc000278aa0}, 0xc0016b2500, {0x2dfc440, 0xc00a1037e8}, 0x0?, 0x0?, 0xc0016b2660, {0x2e16c40, ...}, ...)
	/build/8j4z3vqpxwq9r45xzyj4hj30h1kj55sj-source/vendor/github.com/tendermint/tendermint/node/node.go:772 +0x577
github.com/tharsis/ethermint/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x2e2ceb0, 0xc000270510}, {0x0, 0x0}, {0x2e1a580, 0xc0010c2230}, ...}, ...)
	/build/8j4z3vqpxwq9r45xzyj4hj30h1kj55sj-source/vendor/github.com/tharsis/ethermint/server/start.go:306 +0xd93
github.com/tharsis/ethermint/server.StartCmd.func2(0xc00147f180?, {0xc00151e5a0?, 0x0?, 0x6?})
	/build/8j4z3vqpxwq9r45xzyj4hj30h1kj55sj-source/vendor/github.com/tharsis/ethermint/server/start.go:117 +0x228
github.com/spf13/cobra.(*Command).execute(0xc00147f180, {0xc00151e4e0, 0x6, 0x6})
	/build/8j4z3vqpxwq9r45xzyj4hj30h1kj55sj-source/vendor/github.com/spf13/cobra/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002c0280)
	/build/8j4z3vqpxwq9r45xzyj4hj30h1kj55sj-source/vendor/github.com/spf13/cobra/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/build/8j4z3vqpxwq9r45xzyj4hj30h1kj55sj-source/vendor/github.com/spf13/cobra/command.go:918
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/build/8j4z3vqpxwq9r45xzyj4hj30h1kj55sj-source/vendor/github.com/spf13/cobra/command.go:911
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0?, {0xc000260330, 0x11})
	/build/8j4z3vqpxwq9r45xzyj4hj30h1kj55sj-source/vendor/github.com/cosmos/cosmos-sdk/server/cmd/execute.go:36 +0x1eb
main.main()
	/build/8j4z3vqpxwq9r45xzyj4hj30h1kj55sj-source/cmd/cronosd/main.go:13 +0x2c

```
Thanks

**Comment by dandavid3000** [comment]
This version [cronos_0.8.2_Linux_x86_64.tar.gz](https://github.com/crypto-org-chain/cronos/releases/download/v0.8.2/cronos_0.8.2_Linux_x86_64.tar.gz) gives me this information. Maybe it is the wrong version ?

```
./bin/cronosd version
v0.8.0

```

**Comment by yihuang** [comment]
Do you have the error logs before you restart the node?

**Comment by dandavid3000** [comment]
> Do you have the error logs before you restart the node?

Unfortunately, I do not save logs. As far as I remember, I sent a TX and its nonce is lower than the real nonce 1. 
The node keeps saying Your nonce is number x but it is expected to be x+1. The node is not up-to-date and this error appears. The node then stopped and did not sync anymore.

I hope this can help.

**Comment by yihuang** [comment]
This issue can be triggered by exceeding open file limits, could that be the case?

**Comment by dandavid3000** [comment]
I don't think this is the file limit issue. I already changed it to really big number long time ago.
I also found [this](https://github.com/bnb-chain/node-binary/issues/243) from the internet but it seems there is no solution

**Comment by dandavid3000** [comment]
I checked the open file limits setting and everything was fine.
I downloaded the new pruned data. deleted the old data and resynced the node.
Everything's working fine now

**Comment by yihuang** [comment]
@dandavid3000 did you manually switched the flag `iavl-disable-fastnode` in `app.toml` after upgrade?

**Comment by dandavid3000** [comment]
> @dandavid3000 did you manually switched the flag `iavl-disable-fastnode` in `app.toml` after upgrade?

No I  did not touch the config after upgrading v0.8.2. 
I remember the flag seems to be for slow iavl integration. I don't remember exactly what version includes IAVL and it took me around 24 hours to upgrade to this new system
